---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iamnotafed-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: iamnotafed-frontend
    spec:
      containers:
      - name: iamnotafed-frontend
        image: iamnotafedregistry.azurecr.io/i-am-not-a-frontend-dev_web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: iamnotafed-frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: iamnotafed-frontend
