version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: yarn start

  webpack:
    build: .
    depends_on:
      - web
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: webpack --watch
